- name: Tasks for new instances
  block:
  - name: apt update
    apt:
      update_cache: yes

  - name: apt upgrade
    apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Check if reboot is required
    stat:
      path: /run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    reboot:
    when: reboot_required_file.stat.exists

  - name: Set understandable hostname
    hostname:
      name: "{{ inventory_hostname }}"
  when: ansible_hostname != inventory_hostname

- name: install tools
  apt:
    name:
      - git
      - software-properties-common
      - curl
      - python3
      - python3-pip
      - jq
      - net-tools
      - dnsutils
      - openjdk-11-jre
    update_cache: yes
    state: present

- name: install ansible
  shell:
    cmd: python3 -m pip install ansible==2.9.*

- name: add confluent public key for repo packages.confluent.io
  shell:
    cmd: wget -qO - https://packages.confluent.io/deb/6.1/archive.key | apt-key add -
    warn: false

- name: add confluent apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.confluent.io/deb/6.1 stable main
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: install confluent-community
  apt:
    name: confluent-community-2.13
    update_cache: yes

- name: Generate an OpenSSH keypair
  become: true
  become_user: ubuntu
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
